RazorGoL/Models/CellClickEventData.cs
namespace RazorGoL.Models
{
    public class CellClickEventData
    {
        public int Row { get; set; }
        public int Column { get; set; }
    }
}

RazorGoL/Models/CellClickEventResponse.cs
namespace RazorGoL.Models
{
    public class CellClickEventResponse
    {
        public CellState State { get; set; }
    }
}

RazorGoL/Models/CellState.cs
namespace RazorGoL.Models
{
    public enum CellState
    {   
        Dead,
        Alive
    }
}

RazorGoL/Models/InitializeData.cs
namespace RazorGoL.Models
{
    public class InitializeData
    {
        public int Width { get; set; }
        public int Height { get; set; }
        public int[][]? AliveCells { get; set; }
    }
}

RazorGoL/Models/SimulationState.cs
namespace RazorGoL.Models
{
    public class SimulationState
    {
        private const int defaultDimension = 21;

        public int BoardWidth { get; set; }
        public int BoardHeight { get; set; }

        public CellState[][] Board { get; set; } = null!;

        public static SimulationState GetDefaultState()
        {
            var state = new SimulationState
            {
                BoardHeight = defaultDimension,
                BoardWidth = defaultDimension,
                Board = new CellState[defaultDimension][]
            };

            for (int i = 0; i < defaultDimension; i++)
            {
                state.Board[i] = new CellState[defaultDimension];
            }

            return state;
        }
    }
}

RazorGoL/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace RazorGoL.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RazorGoL/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorGoL.Models;
using RazorGoL.Services;

namespace RazorGoL.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly ISimulationService _simulationService;
        public SimulationState SimulationState { get; set; } = SimulationState.GetDefaultState();

        public IndexModel(ISimulationService simulationService, ILogger<IndexModel> logger)
        {
            _simulationService = simulationService;
            _logger = logger;
        }

        public async Task OnGet()
        {
            SimulationState = await _simulationService.CurrentStateAsync();
        }

        public async Task<IActionResult> OnPostNext()
        {
            SimulationState = await _simulationService.NextStateAsync();

            return Page();
        }

        public async Task<IActionResult> OnPost([FromBody] CellClickEventData data)
        {
            var state = SimulationState = await _simulationService.CurrentStateAsync();
            var aliveCells = new List<int[]>();
            for (int i = 0; i < state.Board.Length; i++)
            {
                for (int j = 0; j < state.Board[i].Length; j++)
                {
                    if (state.Board[i][j] == CellState.Alive)
                        aliveCells.Add(new int[] { i, j });
                }
            }

            var index = aliveCells.FindIndex(item => item[0] == data.Row && item[1] == data.Column);

            if (index == -1)
            {
                aliveCells.Add(new int[] { data.Row, data.Column });
            }
            else
            {
                aliveCells.RemoveAt(index);
            }

            await _simulationService.SetStateAsync(new InitializeData
            {
                Height = state.BoardHeight,
                Width = state.BoardWidth,
                AliveCells = aliveCells.ToArray()
            });

            return new OkObjectResult(new CellClickEventResponse { State = index == -1 ? CellState.Alive : CellState.Dead });
        }
    }
}

RazorGoL/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorGoL.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RazorGoL/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<script src="~/js/site.js"></script>

<div class="table-container">
    <div class="button-container">
        <button class="btn">Start</button>
        <button class="btn">Stop</button>
        <form method="post">
            <button type="submit" class="btn" asp-page-handler="Next">Next</button>
        </form>
    </div>
    <div>
        <table class="board-table">
            <tbody>
                @for (int i = 0; i < Model.SimulationState.Board.Length; i++)
                {
                    <tr>
                        @for (int j = 0; j < Model.SimulationState.Board[i].Length; j++)
                        {
                            string cellClass = Model.SimulationState.Board[i][j] == Models.CellState.Alive ?
                            "alive-cell" : "dead-cell";

                            <td>
                                <div id="@i-@j" class="cell @cellClass" onclick="onCellClick(event)" />
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

RazorGoL/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorGoL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RazorGoL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RazorGoL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RazorGoL - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>